CREATE SCHEMA webuser
    AUTHORIZATION postgres;

COMMENT ON SCHEMA webuser
    IS 'Schema para web app';

CREATE TABLE WEBUSER.INSTRUTORES (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    sobrenome VARCHAR(255) NOT NULL,
    data_nascimento DATE NOT NULL,
    endereco TEXT,
    telefone VARCHAR(255) NOT NULL
);

CREATE TABLE WEBUSER.PLANOS (
    id SERIAL PRIMARY KEY,
    plano VARCHAR(255) NOT NULL,
);

CREATE TABLE WEBUSER.ALUNOS (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    sobrenome VARCHAR(255) NOT NULL,
    data_nascimento DATE NOT NULL,
    endereco TEXT,
    telefone VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    tipo_plano INTEGER REFERENCES WEBUSER.PLANOS(id),
    data_inicio DATE NOT NULL,
    ativo BOOLEAN NOT NULL
);

CREATE TABLE WEBUSER.ATIVIDADES (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    instrutor INTEGER REFERENCES WEBUSER.INSTRUTORES(id) ON DELETE CASCADE,
    data TIMESTAMP NOT NULL,
    duracao INT NOT NULL,
    capacidade INT NOT NULL,
    tipo_plano INT REFERENCES WEBUSER.PLANOS(id),
    ativo BOOLEAN NOT NULL
);

CREATE TABLE WEBUSER.AGENDAMENTOS (
    id SERIAL PRIMARY KEY,
    atividade INTEGER REFERENCES WEBUSER.ATIVIDADES(id) ON DELETE CASCADE,
    membro INTEGER REFERENCES WEBUSER.ALUNOS(id) ON DELETE CASCADE
);


    

